[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Configuration pour les fonctions serverless (API routes)
[functions]
  timeout = 360
  included_files = ["**/*"]

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
